version: "3.8"

services:
  backend:
    image: rpmonback:latest
    container_name: rpmon_back
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: rpmon_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboardrpmon
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rpmon_network

networks:
  rpmon_network:
    driver: bridge

volumes:
  mysql_data:
